FROM node:20-alpine3.20

WORKDIR /usr/src/app

COPY package*.json ./

RUN apk update && apk upgrade && \
    npm install -g @angular/cli && \
    npm install --force

COPY . .

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]